Debug ecs (temporary)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,7 +26,7 @@ jobs:
                 run: composer update --working-dir=tools/ecs --no-interaction --no-progress
 
             -   name: Check the coding style
-                run: composer cs-check
+                run: php tools/ecs/vendor/bin/ecs check --config tools/ecs/config/default.php --no-progress-bar --no-ansi > ecs.log 2>&1 || { echo "::error::$(tail -c 3500 ecs.log | sed "s/%/%25/g" | sed ":a;N;$!ba;s/\n/%0A/g")"; exit 1; }
 
     tests:
         name: PHP ${{ matrix.php }}${{ matrix.dependencies == 'lowest' && ' --prefer-lowest' || '' }}
